### ISSUE TITLE
Vercelにデプロイするとエラーが発生

### ISSUE THREAD

**Issue by chabesu** [chabesu/easy-notion-blog#1]
[Like button updates the Like column in Notion DB #87](https://github.com/otoyo/notion-blog/pull/87/commits/a874597853aa102ca826372734f67f10247f360c)の内容を反映してVercelにデプロイすると、Vercelで以下のエラーが発生。

```
<html>
<body>
<!--StartFragment-->

Cloning github.com/chabesu/easy-notion-blog (Branch: main, Commit: b23aaf5)
--
11:04:05.045 | Cloning completed: 413.006ms
11:04:05.933 | Looking up build cache...
11:04:09.571 | Build cache downloaded [72.01 MB]: 3203.075ms
11:04:09.794 | Running "vercel build"
11:04:10.289 | Vercel CLI 27.3.2
11:04:10.557 | Installing dependencies...
11:04:10.892 | yarn install v1.22.17
11:04:10.958 | [1/4] Resolving packages...
11:04:11.456 | [2/4] Fetching packages...
11:04:26.726 | [3/4] Linking dependencies...
11:04:26.729 | warning " > @typescript-eslint/eslint-plugin@5.26.0" has unmet peer dependency "@typescript-eslint/parser@^5.0.0".
11:04:44.077 | [4/4] Building fresh packages...
11:04:44.358 | success Saved lockfile.
11:04:44.364 | Done in 33.48s.
11:04:44.395 | Detected Next.js version: 12.1.0
11:04:44.396 | Running "yarn run build"
11:04:44.662 | yarn run v1.22.17
11:04:44.689 | $ node scripts/set-blog-index-cache.js && next build && node scripts/expire-blog-index-cache.js
11:04:45.269 | Cached 11 posts into /vercel/path0/.blog_index_data
11:04:45.946 | info  - Checking validity of types...
11:04:45.954 | It looks like you're trying to use TypeScript but do not have the required package(s) installed.
11:04:45.954 |  
11:04:45.954 | Please install @types/react by running:
11:04:45.954 |  
11:04:45.955 | yarn add --dev @types/react
11:04:45.955 |  
11:04:45.956 | If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).
11:04:45.956 |  
11:04:45.980 | error Command failed with exit code 1.
11:04:45.980 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
11:04:46.110 | Error: Command "yarn run build" exited with 1

<!--EndFragment-->
</body>
</html>
```

### やったこと
以下のパッケージをアップグレードしたが、開発環境（yarn dev）しても上記と同じエラーが発生するようになった。
`yarn add typescript @types/node @types/react @types/react-dom @types/jest`

### 過去のコミットに戻っても同様のエラーが出るようになった
エラーが出ていなかったコミットに戻って、`yarn dev`を行っても同様のエラーが出るようになった。  
現状の`package.json`は以下。
ダウングレードしたら正常に戻る？

```
{
  "name": "easy-notion-blog",
  "license": "MIT",
  "version": "0.1.1",
  "scripts": {
    "dev": "next dev",
    "start": "next start",
    "build": "node scripts/set-blog-index-cache.js && next build && node scripts/expire-blog-index-cache.js",
    "format": "prettier --write \"**/*.{js,jsx,json,ts,tsx,md,mdx,css,html,yml,yaml,scss,sass}\" --ignore-path .gitignore",
    "lint": "next lint",
    "test": "jest --watch"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "dependencies": {
    "@dhaiwat10/react-link-preview": "^1.14.0",
    "@notionhq/client": "^1.0.4",
    "@types/jest": "^28.1.6",
    "@types/mermaid": "^8.2.9",
    "@types/react-dom": "^18.0.6",
    "axios": "^0.27.2",
    "image-size": "^1.0.1",
    "mermaid": "^9.1.1",
    "next": "12",
    "prismjs": "^1.28.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-share": "^4.4.0",
    "react-twitter-embed": "^4.0.4",
    "react-youtube": "^9.0.2",
    "shell-quote": "^1.7.3",
    "swr": "^1.3.0"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.5",
    "@types/node": "^18.6.2",
    "@types/prismjs": "^1.26.0",
    "@types/react": "^18.0.15",
    "@typescript-eslint/eslint-plugin": "^5.26.0",
    "eslint": "8.16.0",
    "eslint-config-next": "^12.1.6",
    "husky": "^8.0.1",
    "jest": "^27.5.1",
    "lint-staged": "^12.4.2",
    "node-mocks-http": "^1.11.0",
    "prettier": "^2.6.2",
    "typescript": "^4.7.4"
  }
}
```

**Comment by otoyo** [comment]
`package.json` から `@types/mermaid` を削除していただけますでしょうか？
もしそれでもダメでしたら、ローカルで `yarn build` コマンドを実行して、出たエラーをまた貼っていただけますでしょうか？

**Comment by chabesu** [comment]
`package.json` から `@types/mermaid` を削除したのですが、同様のエラーが出てしまいました。

**Comment by otoyo** [comment]
APIトークンが違っているようですね。
`NOTION_API_SECRET` 環境変数を本番と同じものをローカルにも設定して再度 `yarn build` 試していただけますか？
環境変数を設定するには `.env.local` に記述するか、`export NOTION_API_SECRET=aaa` のようにします。

**Comment by otoyo** [comment]
セキュリティもあるので👆 に貼っていただいたログは消しておいてくださいませ。

**Comment by chabesu** [comment]
ありがとうございます！  
`NOTION_API_SECRET` 環境変数はエラーが出る前と何も変えておらず、今も確認してみましたが、本番とローカルで同じでした（本番：Vercelで確認、ローカル：`.env.local` に記述）。  
再度 `yarn build` してみましたが、同じエラーが出てしまいました。  
もう少し、原因探ってみます。
本当にありがとうございます！！

**Comment by otoyo** [comment]
コミットを戻してもエラーが出ているということなので、コードとは関係ない部分が原因になってそうな気がします。

となると Notion か Vercel ですが、Vercel は 👆 で確認いただいたので、Notion データベースにインテグレーションが追加されているか、もしくは再度インテグレーションを追加し直して `NOTION_API_SECRET` を設定し直していただくのがよさそうです。

**Comment by otoyo** [comment]
easy-notion-blog 本家の方は最新の main ブランチで `yarn build` が通ることは確認しております。

**Comment by chabesu** [comment]
そこまで確認していただいて本当にありがとうございます！
お手数おかけして申し訳ないです。
とりあえず、ブログの更新はNotion側の記事を更新したらできました。
Notion側もインテグレーション削除して追加しなおしたりしてみたのですが、解決できませんでした。
もう少し、じっくりと時間をかけて考えてみます。
本当にお手間おかけして申し訳ないです。
ありがとうございました！！

**Comment by chabesu** [comment]
### 途中経過
`.env.local`は今までと同じ`NOTION_API_SECRET`と`DATABASE_ID`を入れていた。   
しかし、`yarn build`を実行してみると、`path failed validation: path.database_id should be a valid uuid, instead was `"undefined"`.`が返ってくる。  
試しに`export DATABASE_ID=***`を入れてみると、上記のエラーは無くなったが、今度は以下のエラーが発生。  

```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

        yarn add --dev @types/react
```

原因調査中。

### 疑問点
今までと.env.localは変えていないのに、なぜ急にエラーが発生するようになったのか。  
`export DATABASE_ID=***`をすると  
`path failed validation: path.database_id should be a valid uuid, instead was `"undefined"`.`  
が発生しなくなったということは、.env.localが読み込めていなかったということか。  
原因調査中。

**Comment by otoyo** [comment]
> path.database_id should be a valid uuid

このエラーメッセージはNotion APIクライアントによるもので、意味としてはDATABASE_IDが未定義 undefined になっているというものですね。
なのでチャベスさんの予想通り .env.local がなんらかの理由で読み込めていないものと思われます。

It looks の方のエラーは React が TypeScript  のプロジェクトには types/react による型定義が必要というものですが、すでに package.json にはあるんですよね。
一度 yarn install して改善するか見ていただけますでしょうか？

**Comment by otoyo** [comment]
設定した環境変数をリセットするために一度ターミナルを終了して開き直すのもデバッグに役立つかと思います。

**Comment by chabesu** [comment]
アドバイスありがとうございます！
助かります！

> このエラーメッセージはNotion APIクライアントによるもので、意味としてはDATABASE_IDが未定義 undefined になっているというものですね。
なのでチャベスさんの予想通り .env.local がなんらかの理由で読み込めていないものと思われます。

`console.log`で試してみましたが、.env.local内の環境変数（データベースIDと秘密鍵）が読み込まれていません。
ターミナルを終了したり、PCを再起動したりもしてみたのですが、現状では原因不明です。。。

> It looks の方のエラーは React が TypeScript のプロジェクトには types/react による型定義が必要というものですが、すでに package.json にはあるんですよね。
一度 yarn install して改善するか見ていただけますでしょうか？
ありがとうございます。
試したこととしては、
- types/reactのバージョンアップ
- yarn install
等も試してみました。
しかし、やはり同じエラーが出てしまって、こちらも現状原因不明です。。。

自分的には手つまり感が強くなっているので、一度リポジトリを消して、最新の本家リポジトリからもう一回やり直すということも視野に入れています。

**Comment by otoyo** [comment]
チャベスさんの main ブランチを otoyo/easy-notion-blog の Vercel にデプロイしようとしたところエラーを再現することができました。
今のところ 3206c8361867c305ad02dc0ec8f1cb06cd497022 のコミットまで戻したら正常にデプロイできることは確認しました。このコミット以降でデプロイに失敗する原因がありそうです。

追記:
77cc31fed5b226292076edb7659814c220b921e6 までデプロイできることを確認しました。

追記:
a6f6b9bac2a2427e415c1496724561cfdb84261d までデプロイできることを確認しました。

**Comment by otoyo** [comment]
原因わかりました。 `@types/prismjs` をアンインストールすれば解決します。
ローカルで `git revert 1ea09a8754c6acab4cebd40be179d505c4fe23be` してそのままコミットして push してみてください。

**Comment by chabesu** [comment]
解決しました！！！
本当にありがとうございます！！！
厚かましくて申し訳ありませんが、原因ってなんだったんでしょうか。

**Comment by otoyo** [comment]
`@types/` が付くパッケージは TypeScript のための型定義なので無くても動作には問題ないのですが、以前 `@types/mermaid` を導入したときにもビルドが通らなくなってしまったことがありました。
詳細な原因までは調べてないのでわかりませんが、おそらく型定義と使い方に問題があったのかなと思います。

**Comment by chabesu** [comment]
承知しました。  
@types/prismjsといえば、[Notion code style #102](https://github.com/otoyo/easy-notion-blog/pull/102/commits)のPRで入れたと思うのですが、@types/prismjsをアンインストールすることで、コードカラーへの影響は出ますか？

**Comment by otoyo** [comment]
types 系パッケージは dev インストールなので影響はありません。すでに revert したのでアンインストールしていますね。

**Comment by chabesu** [comment]
ありがとうございます!! 
以下、自分のメモです。自分の中で整理できたらこのissueはクローズしておきます。

# 今回起こった現象
  [Like button updates the Like column in Notion DB #87](https://github.com/otoyo/notion-blog/pull/87/commits/a874597853aa102ca826372734f67f10247f360c)を内容を反映してVercelにデプロイすると、Vercelで以下のエラーが発生。  
その後、ローカル環境で `yarn build` や `yarn dev` を行うと、以下のエラーが出るようになった。
```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

        yarn add --dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

# 対応
@types/prismjs をアンインストールすれば解決した。
@types/prismjsは[Notion code style #102](https://github.com/otoyo/easy-notion-blog/pull/102/commits)のPRを取り込んだ時のコミットなので、`git revert 1ea09a8754c6acab4cebd40be179d505c4fe23be`（@types/prismjsをインストールしたコミットを削除）することで対応。

# 原因
詳細な原因までは不明であるが、おそらく型定義と使い方に問題がある。

# 疑問点
@types/prismjsをインストールした後、しばらくは別の内容をコミットしたり、`yarn dev`したり、Vercelにデプロイしたが、エラーは出ていなかったという記憶。
[Like button updates the Like column in Notion DB #87](https://github.com/otoyo/notion-blog/pull/87/commits/a874597853aa102ca826372734f67f10247f360c)を内容を反映した時点でなぜエラーが出るようになったかは不明。

 以下、開発者の otoyo さんコメント。
> @types/ が付くパッケージは TypeScript のための型定義なので無くても動作には問題ないのですが、以前 @types/mermaid を導入したときにもビルドが通らなくなってしまったことがありました。
詳細な原因までは調べてないのでわかりませんが、おそらく型定義と使い方に問題があったのかなと思います

# 考察（自分用のメモ）
@types/prismjsを削除したが、Notion code styleへの影響はない。  
@types/がつくパッケージは、TyoeScriptの型定義のためのパッケージで、今回でいうとprismjsを型定義するためのパッケージ。  
@types/prismjsを入れない場合（型定義をしない場合）は、型はanyとして扱われるので（全ての型を入れてもOKとなる）、実動作への影響はない。ただし、TypeScriptの恩恵は受けれない。  

## 参考
- [なぜTypeScriptを使うのか？ - TypeScript Deep Dive 日本語版](https://typescript-jp.gitbook.io/deep-dive/getting-started/why-typescript)
- [TypeScriptの型システム - TypeScript Deep Dive 日本語版](https://typescript-jp.gitbook.io/deep-dive/type-system)
- [「@types/」から始まる名前のパッケージとは - Qiita](https://qiita.com/pepo/items/81e2b71b624633ba272e)
- [TypeScript で型定義ファイル( d.ts )がないときの対処法 - Qiita](https://qiita.com/Nossa/items/726cc3e67527e896ed1e)
